[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "pep621"
update_changelog_on_bump = true

[tool.yamlfix]
line_length = 120
explicit_start = false
sequence_style = "keep_style"
whitelines = 1
section_whitelines = 1
