#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034

setopt globdots

### ? OMZ ###

# syntax-highlighting must be the last plugin sourced
plugins=(git git-lfs gitignore fzf brew docker docker-compose helm terraform aws uv rsync ssh ssh-agent pre-commit aliases
  dirhistory encode64 zoxide mise starship python golang rust
  # custom
  forgit fzf-tab you-should-use zsh-autosuggestions zsh-syntax-highlighting)

YSU_MODE=ALL
YSU_HARDCORE=1

forgit_ignore=gi-forgit # differs from `.gitignore` created by Toptal API
forgit_stash_show=gsts  # default `gss` alias conflicts with `git status --short`

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

fpath+="$ZDOTDIR/ohmyzsh/custom/plugins/zsh-completions/src"
autoload -U compinit && compinit

zstyle ':omz:update' mode disabled
source "$ZDOTDIR/ohmyzsh/oh-my-zsh.sh"

# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
zstyle ':completion:*' special-dirs false
zstyle ':completion:*' ignored-patterns '*.DS_Store' '*.idea'
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':fzf-tab:*' switch-group '<' '>'
zstyle ':fzf-tab:*' fzf-flags --height=12
zstyle ':fzf-tab:*' use-fzf-default-opts yes
zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'

bindkey "^I" autosuggest-accept # tab
bindkey "^[[Z" fzf-tab-complete # shift-tab

# shift-arrow:
bindkey "^[[1;2A" dirhistory_zle_dirhistory_down
bindkey "^[[1;2B" dirhistory_zle_dirhistory_up
bindkey "^[[1;2C" dirhistory_zle_dirhistory_future
bindkey "^[[1;2D" dirhistory_zle_dirhistory_back

### ? OTHER ###

source "$ZDOTDIR/exports.sh"
source "$ZDOTDIR/aliases.sh"

### ? BOTTOM ###

eval "$(atuin init zsh)"

[ -f "$HOME/.ghcup/env" ] && . "$HOME/.ghcup/env" # ghcup-env
