repositories:
  - name: cilium
    url: https://helm.cilium.io
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: external-secrets
    url: https://charts.external-secrets.io

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    values:
      - hubble:
          relay:
            enabled: true
          ui:
            enabled: true
      - kubeProxyReplacement: true
      - routingMode: native
      - ipam:
          mode: kubernetes
      - ipv4NativeRoutingCIDR: 10.244.0.0/16
      - autoDirectNodeRoutes: true
      - bpf:
          masquerade: true
      - ipMasqAgent:
          enabled: true
          config:
            nonMasqueradeCIDRs:
              - 10.244.0.0/8
    wait: true
    waitForJobs: true

  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    set:
      - name: args[0]
        value: --kubelet-insecure-tls
      - name: existingArgsAppend
        value: true

  - name: external-secrets
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    installed: false
