[tools]
bun = "latest"
"gem:bashly" = "latest"
helm = "latest"
java = "graalvm-community-21"
kubectl = "latest"
node = "latest"
"npm:ghosttime" = "latest"
ruby = "latest"
terraform = "latest"

[settings]
experimental = true

[settings.npm]
bun = true
